### PR TITLE
Update BYON-CallHandling-Service.yaml - 201 session created, 200 session updated, 204 session updated & examples 

### PR DESCRIPTION
**Pull request by deepakjaiswal1**
#### What type of PR is this?
This PR updates the Swagger documentation for the BYON-CallHandling-Service:
a) Adds a 201 Created response for the (POST) VoIP session creation.
b) Adds a 204 No Content response for updating (PUT) VoIP session status when no response body is received.
c) Updates the 200 OK response for updating (PUT) VoIP session status when a response body is received.
d) Adds examples.

### CODE REVIEW

**Comment by deepakjaiswal1** [comment]
@pradeepachar-mavenir @TEF-RicardoSerr Please review the changes in this PR.

**Review by pradeepachar-mavenir — DISMISSED** [review]

**Review by TEF-RicardoSerr — CHANGES_REQUESTED** [review]
As commented in the meeting, looks good overall, it is just needed to adreess the errors raised by megalinter

**Comment by deepakjaiswal1** [comment]
@TEF-RicardoSerr @pradeepachar-mavenir Removed MegaLinter errors.

**Review by TEF-RicardoSerr — APPROVED** [review]
LGTM

**Pull request merged**
