### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by TEF-RicardoSerr**
#### What type of PR is this?

Add one of the following kinds:
* subproject management

#### What this PR does / why we need it:
As some of you are aware I won't be able to keep the chairing of this project. I am proposing @stroncoso-quobis to be chair if any objections. Anyhow I find it is usefull to have him as a CODEOWNER
@camaraproject/admins please send him an invitation

### CODE REVIEW

**Comment by hdamker** [comment]
@TEF-RicardoSerr Thanks for taking care of the succession, highly appreciated! @stroncoso-quobis is already a member of the CAMARA organization, I will add him to the Codewoner team as soon as this PR is ready to be merged

@camaraproject/web-rtc_maintainers Deciding about Codeowners is one of the responsibilities of the Sub Project maintainers. Please approve this PR to support @stroncoso-quobis as Codeowner or raise any objections until Wednesday, August 28th, eob.

**Comment by eharrison24** [comment]
Hi Ricardo,

As Herbert mentioned, once this is merged we can add Santiago.

Best,
Evan

**Comment by hdamker** [comment]
Codeowner file is valid and there were no objections.

**Review by hdamker — APPROVED** [review]
Codeowner file is valid and there were no objections.

**Pull request merged**
