### PR TITLE
Flow review - BYON

### LINKED ISSUE #18: Describe the callflow for using these APIs
**Problem description**
It's not clear how to used these APIs

What is the rule of Registration and Connection Management
**Expected action**
Create some explanations or callflow to describe how to used it

### PR DESCRIPTION
**Pull request by stroncoso-quobis**
#### What type of PR is this?

* documentation

#### What this PR does / why we need it:

- It covers the detailed BYON flow, separated on two main use cases: registration and call handling.
- It provides a necessary asset to attract developers and to fully understand the API mechanisms.

#### Which issue(s) this PR fixes:

Fixes #18 #32

#### Special notes for reviewers:

- Overseeds PR #21 
- Provides more detail regarding method headers, body and complimentary communications

#### Changelog input

```
taks(doc): Splitted diagrams and participant description included
```

#### Additional documentation 

Included exported UML diagrams for easier review

-- Registration / De-registration--
BYON Registration 0 1 2

-- Notification channel --
BYON NotificationChannel 0 1 2

-- Call handling (Originating / Terminating) --
BYON Callhandling 0 1 2

### CODE REVIEW

**Comment by stroncoso-quobis** [comment]
Starting with changes on the Notification process following shared MoMs

**Comment by stroncoso-quobis** [comment]
Updated documentation, registration / notification diagram considered done.

**Comment by stroncoso-quobis** [comment]
Updated after today's meeting. Really appreciate feedback on salmon notes of the diagram.

**Comment by stroncoso-quobis** [comment]
Also considering splitting Registration(RACM) / Notification / CallHandling use cases. They are separate stages, working in parallel or dependant, but, to work with smaller images/documents will benefit all.

**Comment by stroncoso-quobis** [comment]
Blocked due lack of status definition:
* https://github.com/camaraproject/WebRTC/issues/32

And blocked due JSON ACK definition. If we are talking about confirm status changes or to modify the SDP, an PUT/PATCH sould be the way. It must be valid for all notification channel mechanisms (websocket, PSN or webhook)
To discuss related with:
* https://github.com/camaraproject/WebRTC/issues/24
*

**Comment by stroncoso-quobis** [comment]
- Updated to latest API version (headers and parameters)
- Improved terminating flow
- Uniform path on requests
- Included base documentation for status

**Comment by stroncoso-quobis** [comment]
Ready for merge after review commented today on the meeting.

Following https://github.com/camaraproject/WebRTC/pull/29/ session ID identificators
Also fixed compilation of the PlanUML image of call handling, a little big too long.

cc.: @deepakjaiswal1 @TEF-RicardoSerr 

Regards,

**Comment by deepakjaiswal1** [comment]
@stroncoso-quobis @TEF-RicardoSerr  
Please find my comments below:
-- Registration / De-registration--
Flow #4: We need to highlight that channelId is provided only when the channel is externally created, meaning not by the WebRTC Gateway. If the notification channel is an independent service (i.e., not part of the WebRTC Gateway), it should be set up before the RACM session.
-- Notification channel --
Flow # 6: There is no URL for PNS channel. There could be other params along with registrationToken.
-- Call handling (Originating / Terminating) --
Can we capture SIP UPDATE flow also?

**Comment by deepakjaiswal1** [comment]
@stroncoso-quobis Can we also capture call-flow call hold & resume? 
@pradeepachar-mavenir  @TEF-RicardoSerr For the PUT request to /vvoip/{apiVersion}/sessions/{vvoipSessionId}/status, there are two scenarios: (a) the session is updated with no response body, and (b) the session is updated with a response body. I suggest using status code 204 for updates with no response body, and status code 200 for updates that include a response body.

**Comment by stroncoso-quobis** [comment]
Hi @deepakjaiswal1 , reviewed flows after your revision
- Included more detailed and accourate (v0.1.2) info about notification channels
- Included more detail about UPDATE / PRACK on pre-ringing stages for IMS

Check updated UML renders on the PR description.

About the 204/200 in response to PUT actions, I suggest to keep the flow as it is to explain the base concept and get more in detail, maybe on the Markdown plan document or in the openApi description. Under that point of view, I consider that a "generic 204" is ok for this flow overview.

Regarding the call-flow call hold & resume I agree that it is a great resource to add. I can do it, but I suggest creating a new call flow file on a separate PR and try to touch base with this one.

Thanks for your comments! :bow:

**Pull request merged**
